/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.UserHistory;
import ui.LoginJFrame;
import ui.UserLoginJFrame;

/**
 *
 * @author sanal
 */
public class AdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    
    UserHistory history;
    
    public AdminJFrame() {
        initComponents();
        
        history = new UserHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnAdminview = new javax.swing.JButton();
        btnAdminupdate = new javax.swing.JButton();
        btnLoginAgain = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdminview.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdminview.setText("View Persons");
        btnAdminview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminviewActionPerformed(evt);
            }
        });

        btnAdminupdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdminupdate.setText("Create Person");
        btnAdminupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminupdateActionPerformed(evt);
            }
        });

        btnLoginAgain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoginAgain.setText("User Login");
        btnLoginAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminupdate)
                    .addComponent(btnAdminview)
                    .addComponent(btnLoginAgain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminupdate, btnAdminview, btnLoginAgain});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnAdminupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdminview)
                .addGap(173, 173, 173)
                .addComponent(btnLoginAgain)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdminupdate, btnAdminview, btnLoginAgain});

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1407, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminviewActionPerformed
        // TODO add your handling code here:
        
        AdminViewProfileJPanel adminviewPanel = new AdminViewProfileJPanel(history);
        splitPane.setRightComponent(adminviewPanel);
    }//GEN-LAST:event_btnAdminviewActionPerformed

    private void btnAdminupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminupdateActionPerformed
        // TODO add your handling code here:
        
        AdminCreateProfileJPanel adminupdatePanel = new AdminCreateProfileJPanel(history);
        splitPane.setRightComponent(adminupdatePanel);
    }//GEN-LAST:event_btnAdminupdateActionPerformed

    private void btnLoginAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAgainActionPerformed
        // TODO add your handling code here:
        UserLoginJFrame logoutAdmin = new UserLoginJFrame(history);
        logoutAdmin.setVisible(true);
        
    }//GEN-LAST:event_btnLoginAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminupdate;
    private javax.swing.JButton btnAdminview;
    private javax.swing.JButton btnLoginAgain;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
