/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.User;
import model.UserHistory;

/**
 *
 * @author sanal
 */
public class UserLoginJFrame extends javax.swing.JFrame {

    User user;
    static UserHistory userHistory;
    User loggedInUser = null;
    
    ArrayList<String> passwordHistory;
    
    /**
     * Creates new form UserLoginJFrame
     */
    public UserLoginJFrame(UserHistory userHistory) {
        initComponents();
        this.userHistory = userHistory;
        this.passwordHistory = new ArrayList<>();
        
        
        lblUserinfo.setVisible(false);
        lblDob.setVisible(false);
        lblEmail.setVisible(false);
        lblFirstname.setVisible(false);
        lblLastname.setVisible(false);
        lblNeuid.setVisible(false);
        lblPassword1.setVisible(false);
        lblPhone.setVisible(false);
        lblUsername1.setVisible(false);
        txtDob.setVisible(false);
        txtEmail.setVisible(false);
        txtFirstname.setVisible(false);
        txtLastname.setVisible(false);
        txtNeuid.setVisible(false);
        txtPassword.setVisible(false);
        txtPhone.setVisible(false);
        txtUsername1.setVisible(false);
        btnSaveUser.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pswPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblUsername1 = new javax.swing.JLabel();
        txtNeuid = new javax.swing.JTextField();
        lblPassword1 = new javax.swing.JLabel();
        lblNeuid = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtDob = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblUserinfo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        btnSaveUser = new javax.swing.JButton();
        txtLastname = new javax.swing.JTextField();
        txtUsername1 = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setText("Password:");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pswPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername1.setText("Username:");

        txtNeuid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword1.setText("Password:");

        lblNeuid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNeuid.setText("NEU ID:");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDob.setText("Date Of Birth:");

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhone.setText("Phone:");

        lblUserinfo.setBackground(new java.awt.Color(204, 204, 255));
        lblUserinfo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblUserinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserinfo.setText("User Information");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblFirstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFirstname.setText("First Name:");

        btnSaveUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSaveUser.setText("Save");
        btnSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserActionPerformed(evt);
            }
        });

        txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUsername1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblLastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLastname.setText("Last Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUserinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(674, 674, 674)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnLogin)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(666, 666, 666)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPassword1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUsername1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPhone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNeuid)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNeuid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLastname)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFirstname)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnSaveUser)))
                .addContainerGap(672, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogin, lblPassword, lblUsername, pswPassword, txtUsername});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSaveUser, lblDob, lblEmail, lblFirstname, lblLastname, lblNeuid, lblPassword1, lblPhone, lblUsername1, txtDob, txtEmail, txtFirstname, txtLastname, txtNeuid, txtPassword, txtPhone, txtUsername1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnLogin)
                .addGap(36, 36, 36)
                .addComponent(lblUserinfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNeuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNeuid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addComponent(btnSaveUser)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogin, lblPassword, lblUsername, pswPassword, txtUsername});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSaveUser, lblDob, lblEmail, lblFirstname, lblLastname, lblNeuid, lblPassword1, lblPhone, lblUsername1, txtDob, txtEmail, txtFirstname, txtLastname, txtNeuid, txtPassword, txtPhone, txtUsername1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String password = new String(pswPassword.getPassword()); 
        String username = txtUsername.getText();
    
        if (username.contains("admin") && password.contains("admin123")) {
            AdminJFrame AdminInfo = new AdminJFrame();
            AdminInfo.setVisible(true);
            return;
        }

    boolean isAuthenticated = false;

    for (User user : userHistory.getHistory()) {
                
        if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
            if (user.getStatus().equalsIgnoreCase("person")) {
                
                lblUserinfo.setVisible(false);
                lblDob.setVisible(false);
                lblEmail.setVisible(false);
                lblFirstname.setVisible(false);
                lblLastname.setVisible(false);
                lblNeuid.setVisible(false);
                lblPassword1.setVisible(false);
                lblPhone.setVisible(false);
                lblUsername1.setVisible(false);
                txtDob.setVisible(false);
                txtEmail.setVisible(false);
                txtFirstname.setVisible(false);
                txtLastname.setVisible(false);
                txtNeuid.setVisible(false);
                txtPassword.setVisible(false);
                txtPhone.setVisible(false);
                txtUsername1.setVisible(false);
                btnSaveUser.setVisible(false);
                JOptionPane.showMessageDialog(this, "This person is not a user and can't login.");
                return; 
            }

            isAuthenticated = true;
            loggedInUser = user;
            break;
        }
    }
    
    
    loggedInUser = null;

    for (User user : userHistory.getHistory()) {        
        
        if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
            isAuthenticated = true;
            loggedInUser = user;
            break;
        }
    }
    
    if (isAuthenticated && loggedInUser != null) { 
        passwordHistory.add(loggedInUser.getPassword());
    }

    if (isAuthenticated && loggedInUser != null) { 
        
        lblUserinfo.setVisible(true);
        lblDob.setVisible(true);
        lblEmail.setVisible(true);
        lblFirstname.setVisible(true);
        lblLastname.setVisible(true);
        lblNeuid.setVisible(true);
        lblPassword1.setVisible(true);
        lblPhone.setVisible(true);
        lblUsername1.setVisible(true);
        txtDob.setVisible(true);
        txtEmail.setVisible(true);
        txtFirstname.setVisible(true);
        txtLastname.setVisible(true);
        txtNeuid.setVisible(true);
        txtPassword.setVisible(true);
        txtPhone.setVisible(true);
        txtUsername1.setVisible(true);
        btnSaveUser.setVisible(true);
        
        txtUsername1.setText(loggedInUser.getUsername());
        txtPassword.setText(loggedInUser.getPassword());
        txtFirstname.setText(loggedInUser.getFirstname());
        txtLastname.setText(loggedInUser.getLastname());
        txtNeuid.setText(loggedInUser.getNeuid());
        txtDob.setText(loggedInUser.getDob());
        txtPhone.setText(loggedInUser.getPhone());
        txtEmail.setText(loggedInUser.getEmail());

        JOptionPane.showMessageDialog(this, "Welcome, " + loggedInUser.getFirstname() + "!");
    } else {

        lblUserinfo.setVisible(false);
        lblDob.setVisible(false);
        lblEmail.setVisible(false);
        lblFirstname.setVisible(false);
        lblLastname.setVisible(false);
        lblNeuid.setVisible(false);
        lblPassword1.setVisible(false);
        lblPhone.setVisible(false);
        lblUsername1.setVisible(false);
        txtDob.setVisible(false);
        txtEmail.setVisible(false);
        txtFirstname.setVisible(false);
        txtLastname.setVisible(false);
        txtNeuid.setVisible(false);
        txtPassword.setVisible(false);
        txtPhone.setVisible(false);
        txtUsername1.setVisible(false);
        btnSaveUser.setVisible(false);
        
        JOptionPane.showMessageDialog(this, "Incorrect username or password. Please try again.");
    }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserActionPerformed
        // TODO add your handling code here:

        if (loggedInUser == null) {
            JOptionPane.showMessageDialog(this, "No user is logged in.");
            return;
        }

        String newPass = txtPassword.getText();

        if (!newPass.equals(loggedInUser.getPassword())) {

            if (passwordHistory.contains(newPass)) {
                JOptionPane.showMessageDialog(this, "Password has already been used. Please choose a different password.");
                return;
            }

            loggedInUser.setPassword(newPass);
            passwordHistory.add(newPass);
        }

        loggedInUser.setUsername(txtUsername1.getText());
        loggedInUser.setFirstname(txtFirstname.getText());
        loggedInUser.setLastname(txtLastname.getText());
        loggedInUser.setNeuid(txtNeuid.getText());
        loggedInUser.setDob(txtDob.getText());
        loggedInUser.setPhone(txtPhone.getText());
        loggedInUser.setEmail(txtEmail.getText());
        
        String username = txtUsername1.getText();
        String password = txtPassword.getText();
        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String neuid = txtNeuid.getText();
        String dob = txtDob.getText();
        String phone = txtPhone.getText();
        String email = txtEmail.getText();
        
        if(username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty.");
            return;
        }

        if(password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password can't be empty.");
            return;
        }

        if(firstname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Firstname cannot be empty.");
            return;
        }

        if(lastname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lastname cannot be empty.");
            return;
        }

        if(neuid.isEmpty() || !neuid.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "NEU ID should be numeric and cannot be empty.");
            return;
        }

        if(!dob.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "DOB should be in format YYYY-MM-DD.");
            return;
        }

        if(!phone.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Phone number should be 10 digits.");
            return;
        }

        if(email.isEmpty() || !email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Invalid email address.");
            return;
        }


        JOptionPane.showMessageDialog(this, "Information Updated.");
    }//GEN-LAST:event_btnSaveUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UserLoginJFrame frameInstance = new UserLoginJFrame(new UserHistory());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginJFrame(userHistory).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSaveUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblNeuid;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblUserinfo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtNeuid;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
